kind: pipeline
type: golem
name: hello-world
mode: queue

steps:
- name: echo
  image: 69b8f1cde4b8cf6d2ba6df3d29b4c1ac57beb16aef88e43871726cc6
  commands:
# these commands not working currently!
#  - python -m pip install pylint
#  - python -m pylint
  - python hello.py
  
- name: env-test
  image: 69b8f1cde4b8cf6d2ba6df3d29b4c1ac57beb16aef88e43871726cc6
  commands:
  - python env.py
  environment:
    GOLEM_TEST1: test
    GOLEM_TEST2: 123456
