kind: pipeline
type: golem
name: hello-world
mode: queue

steps:
- name: lint
  image: 87363066af80fa0d211a861dc6073cd969878b1251f954c6b884080a
  commands:
  - pip install -r requirements.txt
  - pylint
  
- name: run
  image: 87363066af80fa0d211a861dc6073cd969878b1251f954c6b884080a
  commands:
  - python hello.py

    # - name: publish
    #   image: # ding hash
    #   commands:
    #   environment:
    #     REGISTRY: ${DOCKER_REGISTRY}
    #     USER: ${DOCKER_USERNAME}
    #     PASSWORD: ${DOCKER_PASSWORD}
